# Generated by Django 4.2.7 on 2023-11-17 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('logo', models.ImageField(max_length=10000, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('status', models.BooleanField(db_index=True, default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(db_index=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('street_address', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('division', models.CharField(max_length=255, null=True)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('model_name', models.SlugField(max_length=255, unique=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10)),
                ('prev_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emi_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('is_stock', models.BooleanField(default=False)),
                ('sold_stock', models.IntegerField(blank=True, default=0)),
                ('total_stock', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, default=None)),
                ('featured', models.BooleanField(default=False)),
                ('display_big', models.BooleanField(db_index=True, default=False, null=True)),
                ('offered', models.BooleanField(default=False)),
                ('offered_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_computer_api.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_computer_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='SideMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('logo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('query', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='global_computer_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubSideMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('side_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_side_menu', to='global_computer_api.sidemenu')),
            ],
        ),
        migrations.CreateModel(
            name='SpecTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=255)),
                ('field_description', models.CharField(db_index=True, max_length=255)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_table', to='global_computer_api.specification')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_text', models.CharField(max_length=255, null=True)),
                ('mid_text', models.CharField(max_length=255, null=True)),
                ('color', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/slider')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_computer_api.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_computer_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('stars', models.IntegerField(db_index=True)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='global_computer_api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='global_computer_api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='side_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='global_computer_api.sidemenu'),
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_description', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='global_computer_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('slogan', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(upload_to='image/slider')),
                ('color', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_computer_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='global_computer_api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_computer_api.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
