# Generated by Django 4.2.7 on 2023-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_computer_api', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
